# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-19 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now_add=True)),
                ('alias_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': '驻地',
                'verbose_name_plural': '驻地',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='local_project_ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_version', models.CharField(max_length=128)),
                ('path', models.CharField(max_length=128)),
                ('backup_path', models.CharField(default='', max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now_add=True)),
                ('local_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.local')),
            ],
            options={
                'verbose_name': '驻地项目关系',
                'verbose_name_plural': '驻地项目关系',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now_add=True)),
                ('alias_name', models.CharField(default='', max_length=128)),
                ('release_version', models.CharField(max_length=128, unique=True)),
                ('release_path', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='update_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=128)),
                ('local', models.CharField(default='', max_length=128)),
                ('project', models.CharField(max_length=128)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('u_time', models.DateTimeField(auto_now_add=True)),
                ('patch_file', models.CharField(max_length=128)),
                ('new_version', models.CharField(default='', max_length=128)),
                ('last_version', models.CharField(default='', max_length=128)),
            ],
            options={
                'verbose_name': '发布工单',
                'verbose_name_plural': '发布工单',
                'ordering': ['host'],
            },
        ),
        migrations.AddField(
            model_name='local_project_ship',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.project'),
        ),
        migrations.AddField(
            model_name='local',
            name='project',
            field=models.ManyToManyField(through='update.local_project_ship', to='update.project'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.local'),
        ),
    ]
