# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update_book',
            options={'ordering': ['-c_time'], 'verbose_name': '发布工单', 'verbose_name_plural': '发布工单'},
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_passwd',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_user_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
