# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0004_auto_20200324_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_version',
            name='u_time',
        ),
    ]
