# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_remove_history_version_u_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_version',
            name='local_project',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='history_version',
            name='local_project_version_ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update.project'),
        ),
    ]
