# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_auto_20200324_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_version',
            old_name='local_project_version_ship',
            new_name='local_project_ship',
        ),
    ]
