# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-03-24 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_auto_20200324_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='update_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('hotfix', '热更新'), ('patch', '小版本'), ('package', '大版本')], default='hotfix', max_length=10)),
            ],
        ),
    ]
